"""
Official legislature URLs for all 50 states + DC.
These are the authoritative source URLs used for scraping and citation.
Owner: Sarah / Agent scraper

Each entry has:
    name:         full state name
    abbr:         2-letter abbreviation
    citation:     canonical citation prefix
    base_url:     official legislature URL
    search_url:   URL pattern for searching vehicle code sections
    code_name:    name of the vehicle/traffic code
    chapters:     known PI-relevant chapter numbers
"""

STATE_SOURCES = [
    {
        "name": "California",
        "abbr": "CA",
        "citation": "Cal. Veh. Code",
        "base_url": "https://leginfo.legislature.ca.gov",
        "search_url": "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=VEH&sectionNum={section}.",
        "code_name": "Vehicle Code",
        "chapters": ["11", "12", "13"],
    },
    {
        "name": "Texas",
        "abbr": "TX",
        "citation": "Tex. Transp. Code",
        "base_url": "https://statutes.capitol.texas.gov",
        "search_url": "https://statutes.capitol.texas.gov/Docs/TN/htm/TN.{chapter}.htm",
        "code_name": "Transportation Code",
        "chapters": ["544", "545", "547", "49"],
    },
    {
        "name": "New York",
        "abbr": "NY",
        "citation": "N.Y. Veh. & Traf. Law",
        "base_url": "https://legislation.nysenate.gov",
        "search_url": "https://legislation.nysenate.gov/api/3/statutes/VTL/{section}",
        "code_name": "Vehicle and Traffic Law",
        "chapters": ["28", "31"],
    },
    {
        "name": "Florida",
        "abbr": "FL",
        "citation": "Fla. Stat.",
        "base_url": "https://www.flsenate.gov",
        "search_url": "https://www.flsenate.gov/Laws/Statutes/{chapter}.{section}",
        "code_name": "Florida Statutes Title XXIII",
        "chapters": ["316", "322"],
    },
    {
        "name": "Illinois",
        "abbr": "IL",
        "citation": "625 Ill. Comp. Stat.",
        "base_url": "https://www.ilga.gov",
        "search_url": "https://www.ilga.gov/legislation/ilcs/ilcs4.asp?ActID=1815&ChapterID=49",
        "code_name": "Illinois Vehicle Code",
        "chapters": ["5/11", "5/6"],
    },
    {
        "name": "Pennsylvania",
        "abbr": "PA",
        "citation": "75 Pa. Cons. Stat.",
        "base_url": "https://www.legis.state.pa.us",
        "search_url": "https://www.legis.state.pa.us/cfdocs/legis/LI/consCheck.cfm?txtType=HTM&ttl=75&div=0&chpt={chapter}",
        "code_name": "Vehicle Code Title 75",
        "chapters": ["33", "37", "38"],
    },
    {
        "name": "Ohio",
        "abbr": "OH",
        "citation": "Ohio Rev. Code",
        "base_url": "https://codes.ohio.gov",
        "search_url": "https://codes.ohio.gov/ohio-revised-code/section-{section}",
        "code_name": "Ohio Revised Code",
        "chapters": ["4511", "4513"],
    },
    {
        "name": "Georgia",
        "abbr": "GA",
        "citation": "Ga. Code Ann.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/georgia/title-40/",
        "code_name": "Georgia Code Title 40",
        "chapters": ["40-6"],
    },
    {
        "name": "North Carolina",
        "abbr": "NC",
        "citation": "N.C. Gen. Stat.",
        "base_url": "https://www.ncleg.gov",
        "search_url": "https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByArticle/Chapter_20/Article_{article}.html",
        "code_name": "Chapter 20 Motor Vehicles",
        "chapters": ["20"],
    },
    {
        "name": "Michigan",
        "abbr": "MI",
        "citation": "Mich. Comp. Laws",
        "base_url": "https://www.legislature.mi.gov",
        "search_url": "https://www.legislature.mi.gov/Laws/MCL/Chapter257",
        "code_name": "Michigan Vehicle Code Act 300",
        "chapters": ["257"],
    },
    {
        "name": "Arizona",
        "abbr": "AZ",
        "citation": "Ariz. Rev. Stat.",
        "base_url": "https://www.azleg.gov",
        "search_url": "https://www.azleg.gov/ars/{section}.htm",
        "code_name": "Arizona Revised Statutes Title 28",
        "chapters": ["28"],
    },
    {
        "name": "Washington",
        "abbr": "WA",
        "citation": "Wash. Rev. Code",
        "base_url": "https://app.leg.wa.gov",
        "search_url": "https://app.leg.wa.gov/rcw/default.aspx?cite={section}",
        "code_name": "Revised Code of Washington Title 46",
        "chapters": ["46"],
    },
    {
        "name": "Colorado",
        "abbr": "CO",
        "citation": "Colo. Rev. Stat.",
        "base_url": "https://leg.colorado.gov",
        "search_url": "https://leg.colorado.gov/sites/default/files/images/olls/crs2023-title-42.pdf",
        "code_name": "Colorado Revised Statutes Title 42",
        "chapters": ["42-4"],
    },
    {
        "name": "Nevada",
        "abbr": "NV",
        "citation": "Nev. Rev. Stat.",
        "base_url": "https://www.leg.state.nv.us",
        "search_url": "https://www.leg.state.nv.us/NRS/NRS-{chapter}.html",
        "code_name": "Nevada Revised Statutes Chapter 484",
        "chapters": ["484A", "484B", "484C"],
    },
    {
        "name": "Oregon",
        "abbr": "OR",
        "citation": "Or. Rev. Stat.",
        "base_url": "https://www.oregonlegislature.gov",
        "search_url": "https://www.oregonlegislature.gov/bills_laws/ors/ors811.html",
        "code_name": "Oregon Revised Statutes Chapter 811",
        "chapters": ["811", "813"],
    },
    {
        "name": "Minnesota",
        "abbr": "MN",
        "citation": "Minn. Stat.",
        "base_url": "https://www.revisor.mn.gov",
        "search_url": "https://www.revisor.mn.gov/statutes/cite/{section}",
        "code_name": "Minnesota Statutes Chapter 169",
        "chapters": ["169"],
    },
    {
        "name": "Virginia",
        "abbr": "VA",
        "citation": "Va. Code Ann.",
        "base_url": "https://law.lis.virginia.gov",
        "search_url": "https://law.lis.virginia.gov/vacode/title46.2/",
        "code_name": "Code of Virginia Title 46.2",
        "chapters": ["46.2-8", "46.2-9"],
    },
    {
        "name": "Massachusetts",
        "abbr": "MA",
        "citation": "Mass. Gen. Laws",
        "base_url": "https://malegislature.gov",
        "search_url": "https://malegislature.gov/Laws/GeneralLaws/PartI/TitleXIV/Chapter90",
        "code_name": "General Laws Chapter 90",
        "chapters": ["90"],
    },
    {
        "name": "New Jersey",
        "abbr": "NJ",
        "citation": "N.J. Stat. Ann.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/new-jersey/title-39/",
        "code_name": "New Jersey Statutes Title 39",
        "chapters": ["39:4"],
    },
    {
        "name": "Indiana",
        "abbr": "IN",
        "citation": "Ind. Code",
        "base_url": "https://iga.in.gov",
        "search_url": "https://iga.in.gov/laws/2023/ic/titles/9#9-21",
        "code_name": "Indiana Code Title 9 Article 21",
        "chapters": ["9-21"],
    },
    {
        "name": "Tennessee",
        "abbr": "TN",
        "citation": "Tenn. Code Ann.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/tennessee/title-55/",
        "code_name": "Tennessee Code Title 55",
        "chapters": ["55-8", "55-10"],
    },
    {
        "name": "Missouri",
        "abbr": "MO",
        "citation": "Mo. Rev. Stat.",
        "base_url": "https://revisor.mo.gov",
        "search_url": "https://revisor.mo.gov/main/OneSection.aspx?section={section}",
        "code_name": "Missouri Revised Statutes Chapter 304",
        "chapters": ["304", "577"],
    },
    {
        "name": "Wisconsin",
        "abbr": "WI",
        "citation": "Wis. Stat.",
        "base_url": "https://docs.legis.wisconsin.gov",
        "search_url": "https://docs.legis.wisconsin.gov/statutes/statutes/346",
        "code_name": "Wisconsin Statutes Chapter 346",
        "chapters": ["346"],
    },
    {
        "name": "Maryland",
        "abbr": "MD",
        "citation": "Md. Code Ann., Transp.",
        "base_url": "https://mgaleg.maryland.gov",
        "search_url": "https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gtr",
        "code_name": "Maryland Transportation Article",
        "chapters": ["21"],
    },
    {
        "name": "South Carolina",
        "abbr": "SC",
        "citation": "S.C. Code Ann.",
        "base_url": "https://www.scstatehouse.gov",
        "search_url": "https://www.scstatehouse.gov/code/title56.php",
        "code_name": "South Carolina Code Title 56",
        "chapters": ["56-5"],
    },
    {
        "name": "Alabama",
        "abbr": "AL",
        "citation": "Ala. Code",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/alabama/title-32/",
        "code_name": "Alabama Code Title 32",
        "chapters": ["32-5", "32-5A"],
    },
    {
        "name": "Louisiana",
        "abbr": "LA",
        "citation": "La. Rev. Stat.",
        "base_url": "https://www.legis.la.gov",
        "search_url": "https://www.legis.la.gov/legis/Law.aspx?d=88166",
        "code_name": "Louisiana Revised Statutes Title 32",
        "chapters": ["32"],
    },
    {
        "name": "Kentucky",
        "abbr": "KY",
        "citation": "Ky. Rev. Stat.",
        "base_url": "https://apps.legislature.ky.gov",
        "search_url": "https://apps.legislature.ky.gov/law/statutes/chapter.aspx?id=39160",
        "code_name": "Kentucky Revised Statutes Chapter 189",
        "chapters": ["189", "189A"],
    },
    {
        "name": "Oklahoma",
        "abbr": "OK",
        "citation": "Okla. Stat.",
        "base_url": "https://www.oscn.net",
        "search_url": "https://www.oscn.net/applications/oscn/Index.asp?ftdb=STOKST47",
        "code_name": "Oklahoma Statutes Title 47",
        "chapters": ["47"],
    },
    {
        "name": "Connecticut",
        "abbr": "CT",
        "citation": "Conn. Gen. Stat.",
        "base_url": "https://www.cga.ct.gov",
        "search_url": "https://www.cga.ct.gov/current/pub/title_14.htm",
        "code_name": "Connecticut General Statutes Title 14",
        "chapters": ["14-218a", "14-227a"],
    },
    {
        "name": "Iowa",
        "abbr": "IA",
        "citation": "Iowa Code",
        "base_url": "https://www.legis.iowa.gov",
        "search_url": "https://www.legis.iowa.gov/law/iowaCode/sections?codeChapter=321",
        "code_name": "Iowa Code Chapter 321",
        "chapters": ["321"],
    },
    {
        "name": "Utah",
        "abbr": "UT",
        "citation": "Utah Code Ann.",
        "base_url": "https://le.utah.gov",
        "search_url": "https://le.utah.gov/xcode/Title41/Chapter6a/41-6a.html",
        "code_name": "Utah Code Title 41 Chapter 6a",
        "chapters": ["41-6a"],
    },
    {
        "name": "Arkansas",
        "abbr": "AR",
        "citation": "Ark. Code Ann.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/arkansas/title-27/",
        "code_name": "Arkansas Code Title 27",
        "chapters": ["27-51"],
    },
    {
        "name": "Mississippi",
        "abbr": "MS",
        "citation": "Miss. Code Ann.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/mississippi/title-63/",
        "code_name": "Mississippi Code Title 63",
        "chapters": ["63-3", "63-11"],
    },
    {
        "name": "Kansas",
        "abbr": "KS",
        "citation": "Kan. Stat. Ann.",
        "base_url": "https://www.kslegislature.org",
        "search_url": "https://www.kslegislature.org/li/b2023_24/statute/008_000_0000_chapter/",
        "code_name": "Kansas Statutes Chapter 8",
        "chapters": ["8-15", "8-16"],
    },
    {
        "name": "New Mexico",
        "abbr": "NM",
        "citation": "N.M. Stat. Ann.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/new-mexico/chapter-66/",
        "code_name": "New Mexico Statutes Chapter 66",
        "chapters": ["66-7", "66-8"],
    },
    {
        "name": "Nebraska",
        "abbr": "NE",
        "citation": "Neb. Rev. Stat.",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/nebraska/chapter-60/",
        "code_name": "Nebraska Revised Statutes Chapter 60",
        "chapters": ["60-6"],
    },
    {
        "name": "Idaho",
        "abbr": "ID",
        "citation": "Idaho Code",
        "base_url": "https://legislature.idaho.gov",
        "search_url": "https://legislature.idaho.gov/statutesrules/idstat/Title49/T49CH8/",
        "code_name": "Idaho Code Title 49",
        "chapters": ["49-8", "49-14"],
    },
    {
        "name": "West Virginia",
        "abbr": "WV",
        "citation": "W. Va. Code",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/west-virginia/chapter-17c/",
        "code_name": "West Virginia Code Chapter 17C",
        "chapters": ["17C"],
    },
    {
        "name": "Hawaii",
        "abbr": "HI",
        "citation": "Haw. Rev. Stat.",
        "base_url": "https://www.capitol.hawaii.gov",
        "search_url": "https://www.capitol.hawaii.gov/hrscurrent/Vol11_Ch0476-0490/HRS0291C/",
        "code_name": "Hawaii Revised Statutes Chapter 291C",
        "chapters": ["291C"],
    },
    {
        "name": "Maine",
        "abbr": "ME",
        "citation": "Me. Rev. Stat.",
        "base_url": "https://legislature.maine.gov",
        "search_url": "https://legislature.maine.gov/statutes/29-A/title29-Ach19sec0.html",
        "code_name": "Maine Revised Statutes Title 29-A",
        "chapters": ["29-A"],
    },
    {
        "name": "New Hampshire",
        "abbr": "NH",
        "citation": "N.H. Rev. Stat.",
        "base_url": "https://www.gencourt.state.nh.us",
        "search_url": "https://www.gencourt.state.nh.us/rsa/html/XXI/265/265-mrg.htm",
        "code_name": "New Hampshire RSA Chapter 265",
        "chapters": ["265", "265-A"],
    },
    {
        "name": "Rhode Island",
        "abbr": "RI",
        "citation": "R.I. Gen. Laws",
        "base_url": "https://law.justia.com",
        "search_url": "https://law.justia.com/codes/rhode-island/title-31/",
        "code_name": "Rhode Island General Laws Title 31",
        "chapters": ["31-14", "31-22", "31-27"],
    },
    {
        "name": "Montana",
        "abbr": "MT",
        "citation": "Mont. Code Ann.",
        "base_url": "https://leg.mt.gov",
        "search_url": "https://leg.mt.gov/bills/mca/title_0610/chapter_0080/parts_index.html",
        "code_name": "Montana Code Title 61",
        "chapters": ["61-8", "61-9"],
    },
    {
        "name": "Delaware",
        "abbr": "DE",
        "citation": "Del. Code Ann.",
        "base_url": "https://delcode.delaware.gov",
        "search_url": "https://delcode.delaware.gov/title21/c041/index.html",
        "code_name": "Delaware Code Title 21",
        "chapters": ["21"],
    },
    {
        "name": "South Dakota",
        "abbr": "SD",
        "citation": "S.D. Codified Laws",
        "base_url": "https://sdlegislature.gov",
        "search_url": "https://sdlegislature.gov/Statutes/32",
        "code_name": "South Dakota Codified Laws Title 32",
        "chapters": ["32-24", "32-23"],
    },
    {
        "name": "North Dakota",
        "abbr": "ND",
        "citation": "N.D. Cent. Code",
        "base_url": "https://www.legis.nd.gov",
        "search_url": "https://www.legis.nd.gov/cencode/t39c10.pdf",
        "code_name": "North Dakota Century Code Title 39",
        "chapters": ["39-10"],
    },
    {
        "name": "Alaska",
        "abbr": "AK",
        "citation": "Alaska Stat.",
        "base_url": "https://www.akleg.gov",
        "search_url": "https://www.akleg.gov/basis/statutes.asp#28.35",
        "code_name": "Alaska Statutes Title 28",
        "chapters": ["28.35", "28.15"],
    },
    {
        "name": "Vermont",
        "abbr": "VT",
        "citation": "Vt. Stat. Ann.",
        "base_url": "https://legislature.vermont.gov",
        "search_url": "https://legislature.vermont.gov/statutes/chapter/23/013",
        "code_name": "Vermont Statutes Title 23",
        "chapters": ["23"],
    },
    {
        "name": "Wyoming",
        "abbr": "WY",
        "citation": "Wyo. Stat. Ann.",
        "base_url": "https://wyoleg.gov",
        "search_url": "https://wyoleg.gov/statutes/compress/title31.pdf",
        "code_name": "Wyoming Statutes Title 31",
        "chapters": ["31-5"],
    },
    {
        "name": "District of Columbia",
        "abbr": "DC",
        "citation": "D.C. Code",
        "base_url": "https://code.dccouncil.gov",
        "search_url": "https://code.dccouncil.gov/us/dc/council/code/titles/50/chapters/23/",
        "code_name": "D.C. Code Title 50",
        "chapters": ["50-23"],
    },
]

# Quick lookup by abbreviation
STATE_BY_ABBR = {s["abbr"]: s for s in STATE_SOURCES}
STATE_BY_NAME = {s["name"]: s for s in STATE_SOURCES}
ALL_STATE_NAMES = [s["name"] for s in STATE_SOURCES]
